global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fluent-bit'
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets: ['fluentbit:2020']
